# Generated by Django 6.0.2 on 2026-03-02 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raksha', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('natural', 'Natural Disaster'), ('man_made', 'Man-made Disaster'), ('health', 'Health Emergency'), ('conflict', 'Conflict/War')], default='natural', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('severity_multiplier', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Disaster Type',
                'verbose_name_plural': 'Disaster Types',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Organization or service name', max_length=200)),
                ('category', models.CharField(choices=[('police', 'Police/Law Enforcement'), ('medical', 'Medical/Ambulance'), ('fire', 'Fire Department'), ('emergency', 'Emergency Services'), ('disaster', 'Disaster Management'), ('ngo', 'NGO'), ('other', 'Other')], default='emergency', help_text='Category of service', max_length=100)),
                ('phone_number', models.CharField(max_length=32)),
                ('alternate_number', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, help_text='Additional information about this contact')),
                ('active', models.BooleanField(default=True)),
                ('available_247', models.BooleanField(default=True)),
                ('languages_supported', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('food', 'Food & Water'), ('medical', 'Medical Supplies'), ('shelter', 'Shelter & Clothing'), ('rescue', 'Rescue Equipment'), ('communication', 'Communication Tools'), ('transport', 'Transportation'), ('financial', 'Financial Aid'), ('other', 'Other')], default='other', max_length=20)),
                ('unit_of_measurement', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Resource Type',
                'verbose_name_plural': 'Resource Types',
            },
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterModelOptions(
            name='crisisrequest',
            options={'ordering': ['-priority_score', '-created_at'], 'verbose_name': 'Crisis Request', 'verbose_name_plural': 'Crisis Requests'},
        ),
        migrations.AlterModelOptions(
            name='volunteerprofile',
            options={'verbose_name': 'Volunteer Profile', 'verbose_name_plural': 'Volunteer Profiles'},
        ),
        migrations.AddField(
            model_name='assignment',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='hours_spent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='assignment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='crisisrequest',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image of the situation', null=True, upload_to='crisis_images/'),
        ),
        migrations.AddField(
            model_name='crisisrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for tracking'),
        ),
        migrations.AddField(
            model_name='crisisrequest',
            name='people_affected',
            field=models.IntegerField(default=1, help_text='Number of people affected'),
        ),
        migrations.AddField(
            model_name='crisisrequest',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crisisrequest',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to video documentation'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='certifications',
            field=models.TextField(blank=True, help_text='Relevant certifications'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='experience_years',
            field=models.IntegerField(default=0, help_text='Years of volunteering experience'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='has_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='languages_spoken',
            field=models.CharField(blank=True, help_text='Languages you can speak', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='primary_skill',
            field=models.CharField(choices=[('medical', 'Medical/First Aid'), ('rescue', 'Search & Rescue'), ('logistics', 'Logistics & Distribution'), ('communication', 'Communication'), ('counseling', 'Counseling/Psychosocial Support'), ('technical', 'Technical Skills'), ('driver', 'Driver/Transportation'), ('translator', 'Translation Services'), ('general', 'General Help')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='tasks_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='total_hours_volunteered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='crisisrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='crisisrequest',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crisis_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crisisrequest',
            name='resources_required',
            field=models.TextField(blank=True, help_text='List required resources'),
        ),
        migrations.AlterField(
            model_name='crisisrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('approved', 'Approved'), ('allocated', 'Allocated'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='submitted', max_length=16),
        ),
        migrations.AlterField(
            model_name='donation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='List your skills (comma separated)'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crisisrequest',
            name='disaster_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='raksha.disastertype'),
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical'), ('extreme', 'Extreme Emergency')], default='warning', max_length=20)),
                ('affected_area', models.CharField(help_text='Location/Area affected', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('radius_km', models.FloatField(default=50, help_text='Alert radius in kilometers')),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disaster_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='raksha.disastertype')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emergency Alert',
                'verbose_name_plural': 'Emergency Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NGOProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('service_areas', models.TextField(help_text='Areas where NGO operates (comma separated)')),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialization', models.ManyToManyField(blank=True, to='raksha.disastertype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_profile', to=settings.AUTH_USER_MODEL)),
                ('available_resources', models.ManyToManyField(blank=True, to='raksha.resourcetype')),
            ],
            options={
                'verbose_name': 'NGO Profile',
                'verbose_name_plural': 'NGO Profiles',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('volunteer', 'Volunteer Feedback'), ('ngo', 'NGO Feedback'), ('system', 'System Feedback')], default='system', max_length=20)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1-5')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='raksha.assignment')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_feedback', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_feedback', to='raksha.volunteerprofile')),
                ('ngo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_feedback', to='raksha.ngoprofile')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.AddField(
            model_name='crisisrequest',
            name='assigned_ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='raksha.ngoprofile'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='affiliated_ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='raksha.ngoprofile'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('alert', 'Emergency Alert'), ('assignment', 'New Assignment'), ('request_update', 'Request Update'), ('donation', 'Donation Received'), ('system', 'System Notification')], default='system', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='Link to related page', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0)),
                ('unit', models.CharField(help_text='Unit of measurement', max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date (if applicable)', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='raksha.ngoprofile')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raksha.resourcetype')),
            ],
            options={
                'verbose_name': 'Resource Inventory',
                'verbose_name_plural': 'Resource Inventories',
            },
        ),
        migrations.CreateModel(
            name='SafetyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('before', 'Before Disaster'), ('during', 'During Disaster'), ('after', 'After Disaster')], default='before', help_text='When this tip should be followed', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disaster_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_tips', to='raksha.disastertype')),
            ],
            options={
                'verbose_name': 'Safety Tip',
                'verbose_name_plural': 'Safety Tips',
                'ordering': ['-priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('capacity', models.IntegerField(help_text='Maximum number of people')),
                ('current_occupancy', models.IntegerField(default=0)),
                ('contact_number', models.CharField(max_length=32)),
                ('facilities', models.TextField(help_text='Available facilities (comma separated)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('full', 'Full Capacity'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disaster_types', models.ManyToManyField(blank=True, to='raksha.disastertype')),
                ('managed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='raksha.ngoprofile')),
            ],
            options={
                'verbose_name': 'Shelter',
                'verbose_name_plural': 'Shelters',
            },
        ),
    ]
