# Generated by Django 6.0.2 on 2026-03-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raksha', '0002_disastertype_emergencycontact_resourcetype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Emergency Contact', 'verbose_name_plural': 'Emergency Contacts'},
        ),
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload receipt or proof of donation', null=True, upload_to='donation_images/'),
        ),
    ]
