# Generated by Django 4.2.8 on 2026-03-11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_default_channels(apps, schema_editor):
    CommunityChannel = apps.get_model('raksha', 'CommunityChannel')
    defaults = [
        ('all-hands', 'All Hands Coordination', 'Cross-role emergency coordination channel.', 'all'),
        ('ngo-ops', 'NGO Operations', 'For NGO/Admin planning and resource allocation.', 'ngo'),
        ('volunteer-hub', 'Volunteer Hub', 'For volunteer updates, field constraints, and support.', 'volunteer'),
        ('user-support', 'User Support', 'For affected users to ask for guidance and updates.', 'user'),
    ]
    for slug, name, description, role_scope in defaults:
        CommunityChannel.objects.get_or_create(
            slug=slug,
            defaults={
                'name': name,
                'description': description,
                'role_scope': role_scope,
                'is_active': True,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('raksha', '0006_crisischatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('role_scope', models.CharField(choices=[('all', 'All Roles'), ('ngo', 'NGO/Admin Only'), ('volunteer', 'Volunteer Only'), ('user', 'Common User Only')], default='all', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Community Channel',
                'verbose_name_plural': 'Community Channels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommunityMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='raksha.communitychannel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Message',
                'verbose_name_plural': 'Community Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('context_tag', models.CharField(default='general', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Chat Message',
                'verbose_name_plural': 'AI Chat Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_default_channels, migrations.RunPython.noop),
    ]
