# Generated by Django 4.2.8 on 2026-03-11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raksha', '0007_communitychat_aichat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocationPing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('browser', 'Browser Geolocation'), ('manual', 'Manual Entry')], default='browser', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Location Ping',
                'verbose_name_plural': 'User Location Pings',
                'ordering': ['-created_at'],
            },
        ),
    ]
