# Generated by Django 3.1.1 on 2026-02-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('ngo', 'NGO'), ('volunteer', 'Volunteer'), ('victim', 'Victim'), ('admin', 'Admin')], default='donor', max_length=16),
        ),
    ]
