# Generated by Django 3.1.1 on 2026-03-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin or NGO'), (2, 'Volunteer'), (3, 'Common User (Need Help)')], default=3),
        ),
    ]
